name: isar_sandbox
description: "Testing Isar"
version: 0.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  build_runner: ^2.4.6
  cached_network_image: ^3.3.0
  collection: ^1.17.2
  connectivity_plus: ^4.0.2
  custom_lint: ^0.5.3
  dio: ^5.3.3
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_flavorizr: ^2.2.1
  flutter_hooks: ^0.20.1
  flutter_lints: ^2.0.3
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_use: ^0.0.4
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  go_router: ^11.1.2
  go_router_builder: ^2.3.3
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.1
  http_mock_adapter: ^0.6.0
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  logging: ^1.2.0
  mocktail: ^1.0.0
  package_info_plus: ^4.1.0
  path_provider: ^2.1.1
  pretty_dio_logger: ^1.3.1
  riverpod_annotation: ^2.1.6
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  stack_trace: ^1.11.0
  very_good_analysis: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  generate: true
